# Generated by Django 4.0.3 on 2022-03-09 12:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 3, 9, 12, 12, 16, 630044, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 3, 9, 12, 12, 16, 630044, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('pages', models.IntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('in_process', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 3, 9, 12, 12, 16, 630044, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 3, 9, 12, 12, 16, 630044, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
            ],
        ),
    ]
